Main()
{
    config\bot_config::Main();
    config\bots_names_config::Main();
    config\gametype_config::Main();
    config\killstreak_config::Main();
    config\perks_config::Main();
    config\rules_config::Main();
    config\shops_config::Main();
    config\tips_config::Main();
    config\voice_config::Main();
    config\weapons_config::Configure();
    config\zombies_on_restart_config::Main();
}
