version: '3.7'
services:
  nl-cod2-zom:
    image: docker.io/rutkowski/cod2:13.4-server1.3-mysql-unsafe
    stdin_open: true
    tty: true
    stop_grace_period: 1s
    ports:
      - 28960:28960
      - 28960:28960/udp
    volumes:
      - ./nl:/cod2/nl:ro
      - ~/cod2/main/1_3:/cod2/main:ro
      - ./library/iwds:/cod2/library:ro
    environment:
      PARAMS_BEFORE: "+exec server.zom.cfg"
      COD2_SET_fs_homepath: "/cod2/home"
      COD2_SET_fs_game: "nl"
      COD2_SET_fs_library: "library"
      COD2_SET_dedicated: 2
      COD2_SET_net_port: 28960
    healthcheck:
      test: [ "CMD", "/cod2/healthcheck.sh" ]
      interval: 3s
      timeout: 3s
      retries: 1
      start_period: 3s
    deploy:
      restart_policy:
        condition: on-failure

networks:
  default:
    name: stack_network
    external: true
