name: Deploy server files to nl-cod2-zom

on:
  workflow_dispatch:
    inputs:
      sha:
        required: false
        type: string

jobs:
  deploy:
    name: Public (Zombies)
    uses: nl-squad/nl-cod2-workflows/.github/workflows/deploy.yml@main
    with:
      profile: public
      branch: main
      sha: ${{ github.event.inputs.sha }}
      pack: true
      set_passwords: true
      rcon_password: ${{ vars.PUBLIC_RCON_PASSWORD }}
      g_password: ${{ vars.PUBLIC_G_PASSWORD }}
      cfg_file: server.zom.cfg
    secrets: inherit
