name: Deploy server files to nl-cod2-zom-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sha:
        required: false
        type: string

jobs:
  deploy:
    name: Dev
    uses: nl-squad/nl-ops/.github/workflows/deploy.yml@main
    with:
      profile: default
      ref: ${{ github.event.inputs.sha }}
    secrets: inherit
