name: Deploy zom server files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment job
    uses: nl-squad/nl-cod2-workflows/.github/workflows/deploy.yml@main
    with:
      profile: zom
      branch: public
    secrets: inherit
