name: Deploy server files to nl-cod2-zom

on:
  workflow_dispatch:
    inputs:
      sha:
        required: false
        type: string

jobs:
  deploy:
    name: Public (Zombies)
    uses: nl-squad/nl-ops/.github/workflows/deploy.yml@main
    with:
      profile: public
      ref: ${{ github.event.inputs.sha }}
    secrets: inherit
