name: Deploy server files to nl-cod2-zom-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sha:
        required: false
        type: string

jobs:
  deploy:
    name: Dev
    uses: nl-squad/nl-cod2-workflows/.github/workflows/deploy.yml@main
    with:
      profile: default
      branch: main
      sha: ${{ github.event.inputs.sha }}
      pack: true
      set_passwords: true
      cfg_file: server.dev.cfg
    secrets: inherit
