name: Restart the server

on:
  workflow_dispatch:
    inputs:
      server:
        type: choice
        description: Which server do you want to restart? (default = dev)
        required: true
        options: 
        - dev
        - public

jobs:
  restart:
    name: ${{ github.event.inputs.server }}
    uses: nl-squad/nl-cod2-workflows/.github/workflows/restart.yml@main
    with:
      profile: ${{ github.event.inputs.server }}
    secrets: inherit
